/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-ui/lib/aside')['default']
    ElAvatar: typeof import('element-ui/lib/avatar')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElCheckboxGroup: typeof import('element-ui/lib/checkbox-group')['default']
    ElCol: typeof import('element-ui/lib/col')['default']
    ElContainer: typeof import('element-ui/lib/container')['default']
    ElDatePicker: typeof import('element-ui/lib/date-picker')['default']
    ElDialog: typeof import('element-ui/lib/dialog')['default']
    ElDropdown: typeof import('element-ui/lib/dropdown')['default']
    ElDropdownItem: typeof import('element-ui/lib/dropdown-item')['default']
    ElDropdownMenu: typeof import('element-ui/lib/dropdown-menu')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElHeader: typeof import('element-ui/lib/header')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElMain: typeof import('element-ui/lib/main')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElPopover: typeof import('element-ui/lib/popover')['default']
    ElRadio: typeof import('element-ui/lib/radio')['default']
    ElRadioGroup: typeof import('element-ui/lib/radio-group')['default']
    ElRow: typeof import('element-ui/lib/row')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElSwitch: typeof import('element-ui/lib/switch')['default']
    ElTimePicker: typeof import('element-ui/lib/time-picker')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Teleport: typeof import('./src/components/Teleport.vue')['default']
  }
}
