/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-ui/lib/aside')['default']
    ElAvatar: typeof import('element-ui/lib/avatar')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElContainer: typeof import('element-ui/lib/container')['default']
    ElDropdown: typeof import('element-ui/lib/dropdown')['default']
    ElDropdownItem: typeof import('element-ui/lib/dropdown-item')['default']
    ElDropdownMenu: typeof import('element-ui/lib/dropdown-menu')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElHeader: typeof import('element-ui/lib/header')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElMain: typeof import('element-ui/lib/main')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
