/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CollapsedMenu: typeof import('./src/components/main/components/side-menu/collapsed-menu.vue')['default']
    copy: typeof import('./src/components/ParentView copy.vue')['default']
    CustomBreadCrumb: typeof import('./src/components/main/components/header-bar/custom-bread-crumb/custom-bread-crumb.vue')['default']
    ElAside: typeof import('element-ui/lib/aside')['default']
    ElComtainer: typeof import('element-ui/lib/comtainer')['default']
    ElContainer: typeof import('element-ui/lib/container')['default']
    ElFooter: typeof import('element-ui/lib/footer')['default']
    ElHeader: typeof import('element-ui/lib/header')['default']
    ElMain: typeof import('element-ui/lib/main')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElMenuItemGroup: typeof import('element-ui/lib/menu-item-group')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElSubMenu: typeof import('element-ui/lib/sub-menu')['default']
    ErrorStore: typeof import('./src/components/main/components/error-store/error-store.vue')['default']
    Fullscreen: typeof import('./src/components/main/components/fullscreen/fullscreen.vue')['default']
    HeaderBar: typeof import('./src/components/main/components/header-bar/header-bar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Language: typeof import('./src/components/main/components/language/language.vue')['default']
    Main: typeof import('./src/components/main/main.vue')['default']
    MainView: typeof import('./src/components/MainView.vue')['default']
    Notice: typeof import('./src/components/main/components/notice/notice.vue')['default']
    NoticeContent: typeof import('./src/components/main/components/notice/noticeContent.vue')['default']
    ParentView: typeof import('./src/components/ParentView.vue')['default']
    ResetPwd: typeof import('./src/components/main/components/user/reset-pwd.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTag: typeof import('./src/components/main/components/tags-nav/scroll-tag.vue')['default']
    SideMenu: typeof import('./src/components/main/components/side-menu/side-menu.vue')['default']
    SideMenuItem: typeof import('./src/components/main/components/side-menu/side-menu-item.vue')['default']
    SiderTrigger: typeof import('./src/components/main/components/header-bar/sider-trigger/sider-trigger.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TagsNav: typeof import('./src/components/main/components/tags-nav/tags-nav.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    User: typeof import('./src/components/main/components/user/user.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
