/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-ui/lib/aside')['default']
    ElAvatar: typeof import('element-ui/lib/avatar')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElComtainer: typeof import('element-ui/lib/comtainer')['default']
    ElContainer: typeof import('element-ui/lib/container')['default']
    ElDivider: typeof import('element-ui/lib/divider')['default']
    ElDropdown: typeof import('element-ui/lib/dropdown')['default']
    ElDropdownItem: typeof import('element-ui/lib/dropdown-item')['default']
    ElDropdownMenu: typeof import('element-ui/lib/dropdown-menu')['default']
    ElFooter: typeof import('element-ui/lib/footer')['default']
    ElHeader: typeof import('element-ui/lib/header')['default']
    ElMain: typeof import('element-ui/lib/main')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElMenuItemGroup: typeof import('element-ui/lib/menu-item-group')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElSubMenu: typeof import('element-ui/lib/sub-menu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
